### ISSUE TITLE
SandboxServiceAsync is missing.

### ISSUE THREAD

**Issue by HansonYe** [kaaproject/sandbox-frame#6]
The Java file 'org.kaaproject.kaa.sandbox.web.shared.services.SandboxServiceAsync' is missing.

**Comment by odovhai** [comment]
This interface is generated by gwt-maven-plugin from `org.kaaproject.kaa.sandbox.web.shared.services.SandboxService`
You can run `mvn clean compile` from the root directory of sandbox-frame app and find the file under **sandbox-frame/web/target/generated-sources/gwt/** _org.kaaproject.kaa.sandbox.web.shared.services.SandboxServiceAsync_
More info about generating Async interfaces you can find here:
https://gwt-maven-plugin.github.io/gwt-maven-plugin/user-guide/async.html
